using System.Resources;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("MathExpressions")]
[assembly: System.Reflection.AssemblyProduct("CalculateX")]
[assembly: System.Reflection.AssemblyDescription("Math expression parser")]
[assembly: System.Reflection.AssemblyCompany("12noon")]
[assembly: System.Reflection.AssemblyCopyright("© 2021 12noon, Stefan K.S. Tucker, © 2015 Paul Welter")]
[assembly: System.Runtime.InteropServices.Guid("348985f4-3fcf-4ec3-b207-6f09e918b297")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("2.0.9.0")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.9.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.0.0")]
[assembly: NeutralResourcesLanguage("en-US")]

internal sealed partial class ThisAssembly {
    
    internal const string AssemblyTitle = "MathExpressions";
    
    internal const string AssemblyProduct = "CalculateX";
    
    internal const string AssemblyDescription = "Math expression parser";
    
    internal const string AssemblyCompany = "12noon";
    
    internal const string AssemblyCopyright = "© 2021 12noon, Stefan K.S. Tucker, © 2015 Paul Welter";
    
    internal const string Guid = "348985f4-3fcf-4ec3-b207-6f09e918b297";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "2.0.0.0";
    
    internal const string AssemblyFileVersion = "2.0.0.0";
    
    internal const string AssemblyInformationalVersion = "2.0.0.0";
    
    private ThisAssembly() {
    }
}
