//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("CalculateX")]
[assembly: System.Reflection.AssemblyProduct("CalculateX")]
[assembly: System.Reflection.AssemblyDescription("Calculator that can parse math expressions.")]
[assembly: System.Reflection.AssemblyCompany("12noon")]
[assembly: System.Reflection.AssemblyCopyright("© 2021 12noon, Stefan K.S. Tucker, © 2015 Paul Welter")]
[assembly: System.Runtime.InteropServices.Guid("43484513-ed81-4a9f-8de4-be3abfe106b0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("2.0.12.0")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.12.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyTitle = "CalculateX";
    
    internal const string AssemblyProduct = "CalculateX";
    
    internal const string AssemblyDescription = "Calculator that can parse math expressions.";
    
    internal const string AssemblyCompany = "12noon";
    
    internal const string AssemblyCopyright = "© 2021 12noon, Stefan K.S. Tucker, © 2015 Paul Welter";
    
    internal const string Guid = "43484513-ed81-4a9f-8de4-be3abfe106b0";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "2.0.0.0";
    
    internal const string AssemblyFileVersion = "2.0.0.0";
    
    internal const string AssemblyInformationalVersion = "2.0.0.0";
    
    private ThisAssembly() {
    }
}
